name: publish
inputs:
  repository-url:
    required: true
    description: The destination package repository URL
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        path: ./dist
    - name: Publish package distributions to PyPI
      # https://github.com/pypa/gh-action-pypi-publish/issues/290
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ inputs.repository-url }}
