on:
  pull_request:
    branches:
      - master

name: CI

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.13", "3.12", "3.11", "3.10", "3.9"]
    runs-on: ubuntu-latest
    environment: pypi-test
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: extractions/setup-just@v2
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install python venv"
        run: "uv sync"

      - name: "Lint and test"
        run: |
          source .venv/bin/activate
          just lint
          just test
          coverage xml

      - uses: codecov/codecov-action@v5
        if: ${{ contains(matrix.python-version, '3.13') }}
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load version into env
        shell: bash
        run: |
          commit_nr=$(git rev-list --all --count)
          echo "Commit Nr.: ${commit_nr}"
          echo "RELEASE_VERSION=0.1.0${{ github.head_ref }}${commit_nr}" >> $GITHUB_ENV

      - uses: ./.github/build
        with:
          package-version: ${RELEASE_VERSION}

  pypi-publish:
    needs: [test, build]
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi-test
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/publish
        with:
          repository-url: ${{ env.REPOSITORY_URL }}
